import { describe, it, expect } from 'vitest';
import {
  stripEmbeddedFrontmatter,
  tomlToMarkdown,
  buildPluginJson,
  buildMarketplacePlugins,
} from './export-claude';

describe('stripEmbeddedFrontmatter', () => {
  it('should remove a leading frontmatter block from content', () => {
    // Given
    const content = '---\ndescription: some title\n---\nActual content here';

    // When
    const result = stripEmbeddedFrontmatter(content);

    // Then
    expect(result).toBe('Actual content here');
  });

  it('should leave content unchanged when there is no frontmatter', () => {
    // Given
    const content = 'No frontmatter here\nJust plain content';

    // When
    const result = stripEmbeddedFrontmatter(content);

    // Then
    expect(result).toBe(content);
  });

  it('should strip only the first frontmatter block and keep the rest', () => {
    // Given
    const content = '---\ndescription: first\n---\nBody\n---\ndescription: second\n---\nMore';

    // When
    const result = stripEmbeddedFrontmatter(content);

    // Then
    expect(result).toBe('Body\n---\ndescription: second\n---\nMore');
  });
});

describe('tomlToMarkdown', () => {
  it('should convert a TOML command with description and prompt to Claude markdown format', () => {
    // Given
    const tomlContent = `
description = "Do something useful"
prompt = """
Perform this action with {{args}}.
"""
    `.trim();

    // When
    const result = tomlToMarkdown(tomlContent, 'my-command');

    // Then
    expect(result).toMatch(/^---\ndescription: "Do something useful"\n---\n/);
    expect(result).toContain('Perform this action with $ARGUMENTS.');
  });

  it('should replace all {{args}} occurrences with $ARGUMENTS', () => {
    // Given
    const tomlContent = `
description = "Multi-arg command"
prompt = """
First: {{args}}. Second: {{args}}.
"""
    `.trim();

    // When
    const result = tomlToMarkdown(tomlContent, 'multi-arg');

    // Then
    const matches = result.match(/\$ARGUMENTS/g) ?? [];
    expect(matches).toHaveLength(2);
    expect(result).not.toContain('{{args}}');
  });

  it('should fall back to the command name as description when TOML has none', () => {
    // Given
    const tomlContent = `
prompt = """
Some prompt content.
"""
    `.trim();

    // When
    const result = tomlToMarkdown(tomlContent, 'fallback-name');

    // Then
    expect(result).toContain('description: "fallback-name"');
  });

  it('should strip embedded frontmatter from the TOML prompt field', () => {
    // Given
    const tomlContent = `
description = "Command with embedded frontmatter"
prompt = """
---
description: inner frontmatter
---
Real prompt content with {{args}}.
"""
    `.trim();

    // When
    const result = tomlToMarkdown(tomlContent, 'embedded-fm');

    // Then
    const lines = result.split('\n');
    // Only one frontmatter block: the outer one generated by tomlToMarkdown
    const fmDelimiters = lines.filter(l => l === '---');
    expect(fmDelimiters).toHaveLength(2);
    expect(result).toContain('Real prompt content with $ARGUMENTS.');
    expect(result).not.toContain('inner frontmatter');
  });

  it('should produce an empty body when the TOML prompt is missing', () => {
    // Given
    const tomlContent = `description = "No prompt"`;

    // When
    const result = tomlToMarkdown(tomlContent, 'no-prompt');

    // Then
    expect(result).toBe('---\ndescription: "No prompt"\n---\n\n\n');
  });
});

describe('buildPluginJson', () => {
  it('should build a plugin.json object from a full plugin definition', () => {
    // Given
    const plugin = { name: 'npm-tools', version: '1.2.3', description: 'Tools for npm' };

    // When
    const result = buildPluginJson(plugin);

    // Then
    expect(result).toEqual({ name: 'npm-tools', version: '1.2.3', description: 'Tools for npm' });
  });

  it('should default version to "0.0.1" when not provided', () => {
    // Given
    const plugin = { name: 'my-plugin', description: 'A plugin' };

    // When
    const result = buildPluginJson(plugin);

    // Then
    expect(result.version).toBe('0.0.1');
  });

  it('should default description to empty string when not provided', () => {
    // Given
    const plugin = { name: 'bare-plugin' };

    // When
    const result = buildPluginJson(plugin);

    // Then
    expect(result.description).toBe('');
  });
});

describe('buildMarketplacePlugins', () => {
  it('should produce one marketplace entry per plugin in the map', () => {
    // Given
    const plugins = {
      'npm-tools': { name: 'npm-tools', version: '0.0.1', description: 'NPM tools' },
      'git-tools': { name: 'git-tools', version: '1.0.0', description: 'Git tools' },
    };

    // When
    const result = buildMarketplacePlugins(plugins);

    // Then
    expect(result).toHaveLength(2);
  });

  it('should map each plugin to its marketplace entry', () => {
    // Given
    const plugins = {
      'npm-tools': { name: 'npm-tools', version: '0.0.1', description: 'NPM tools' },
    };

    // When
    const result = buildMarketplacePlugins(plugins);

    // Then
    expect(result[0]).toEqual({
      name: 'npm-tools',
      version: '0.0.1',
      description: 'NPM tools',
      source: './plugins/npm-tools',
    });
  });

  it('should apply defaults for version and description when absent', () => {
    // Given
    const plugins = {
      'bare-plugin': { name: 'bare-plugin' },
    };

    // When
    const result = buildMarketplacePlugins(plugins);

    // Then
    expect(result[0].version).toBe('0.0.1');
    expect(result[0].description).toBe('');
    expect(result[0].source).toBe('./plugins/bare-plugin');
  });

  it('should return an empty array when given no plugins', () => {
    // Given / When
    const result = buildMarketplacePlugins({});

    // Then
    expect(result).toEqual([]);
  });
});
